# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  working_directory: /tmp/repo
  docker:
    # specify the version you desire here
    - image: cimg/node:16.10.0-browsers
  resource_class: large

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - run:
          name: "Show yarn and node versions"
          command: |
            node --version
            yarn --version
      - checkout
      # cache build artifacts. Use concatenation of all source files as cache
      # key. If there are no changes to src/ and yarn.lock, no need to rebuild
      - run: yarn install
      - persist_to_workspace:
          root: /tmp
          paths:
            - repo      
  prettier:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/
      - run:
          name: 'Check code style with Prettier'
          command: cd /tmp/repo/ && yarn run prettierCheckCircleCI

workflows:
  version: 2
  install_and_prettify:
    jobs:
      - install:
          filters:
            branches:
              ignore: master
      - prettier:
          requires:
            - install
          filters:
            branches:
              ignore: master
